[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "GuildMM"
description = "Restricts matchmaking to users in the same Discord servers as you."
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/GuildMM.dll"
target = "/BepInEx/plugins/GuildMM/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
